### ISSUE TITLE
To do list - milestone 1

### ISSUE THREAD

**Issue by AndresPitta** [UBC-MDS/DSCI_522_Group-308_Used-Cars#1]
Hey @bradentam and @pokrovskyy,

I created a list of the things to do:

**Files to create:**

**Serg**
- [x] Script that downloads the data
- [x] Teamwork contract
- [x] Code of conduct
- [x] Contributing

**Braden**
- [x] Project proposal

**Andres**
- [x] EDA

Remember everything is python!
Thanks for the work!

**Comment by AndresPitta** [comment]
Hey guys,

I finished the EDA.

**Comment by pokrovskyy** [comment]
Great job! I've just submitted Team Contract, Code of Conduct and Contributing documents PR, you're welcome to review them! Download script will come in the evening

**Comment by AndresPitta** [comment]
Thanks Serg, nice job!

Also, We hace vehicles with market prices of more then $300,000,000 usd. Which, checking one by one, I realised are errors. 
I’m gonna remove those values (and explain why) in the EDA.

**Comment by pokrovskyy** [comment]
Makes sense Andres! By the way, we could use this sort of "rule" to remove outliers outside 3 standard deviations - I remember Tom once suggested that as a good practice

**Comment by AndresPitta** [comment]
Ok, Serg, I used the 99th percentile but we can do that too
