### ISSUE TITLE
[URGENT] Wrangling script does not run

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group-308_Used-Cars#35]
![Group308_Error2](https://user-images.githubusercontent.com/19938275/73319348-f6651e80-41f0-11ea-82c5-ee138862625c.PNG)

**Comment by ksedivyhaley** [comment]
Also fix:

- Wrangling script removes outliers before splitting into test/train - splitting should be your first step.
- Script initial summary doesn't describe target argument (but is described under options) - otherwise well documented

Additional feedback: 

- Could use prefix to simplify train/test path arguments
- Is it a good idea to use 0.9 as your default train size, given that this is only appropriate for larger datasets?
- Good use of tests in multiple sub-functions.

**Comment by AndresPitta** [comment]
Fixed, Thanks Kate!
