### ISSUE TITLE
Milestone 3: Mechanics

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group-308_Used-Cars#53]
- Add orca to dependencies
- Consider adding a partial clean_most that removes everything except data/vehicles.csv! (I did this to my local file for convenience)
- Good conversion of test/train scripts to expected format

**Comment by AndresPitta** [comment]
partial_clean command created in the dockerfile. A recommendation to install the packages using anaconda will be added so that plotly installs dependencies to orca.
