### ISSUE TITLE
Milestone 3: Quality (Minor documentation)

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group-308_Used-Cars#55]
- Makefile could use extra comment explaining how the quick model targets work (ie instead of running train_model on the full data you run it on partial data and then use that to build your report)
  - Otherwise well documented!

- Script summary: instead of saying just "and a target" define target (eg "response variable")

**Comment by pokrovskyy** [comment]
This has been addressed, thanks!
