### ISSUE TITLE
Missing documentation - how to run in docker

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_Group-308_Used-Cars#74]
Hey @pokrovskyy @bradentam and @AndresPitta,

I'm not sure what's going on but your repo is missing some crucial documentation - how to run your analysis using a docker container. 

See image below from [milestone 4](https://github.ubc.ca/MDS-2019-20/DSCI_522_dsci-workflows_students/blob/master/release/milestone4/milestone4.md).

Could you please add the two lines of code required to run your analysis to this repo?

![Screen Shot 2020-02-11 at 7 34 15 PM](https://user-images.githubusercontent.com/2507459/74300710-7f0daf80-4d05-11ea-9aa6-f0de93fefa5e.png)

**Comment by AndresPitta** [comment]
Hi Firas, 

We wrote this commands on the makefile so that the user only has to type make run_quick_from_docker and it does the trick.

**Comment by firasm** [comment]
Ah - interesting! Indeed that does work. 

Very nice! 

let me think about whether this is a good idea or bad...

**Comment by AndresPitta** [comment]
Correction

The command is quick_docker 

![4659673B-3913-4CFC-9221-3D69209DAE12](https://user-images.githubusercontent.com/55466626/74301034-97ca9500-4d06-11ea-90ee-739c3791f6f1.jpeg)
![D28C397C-CC0C-4E78-B7B5-112F02C78CD7](https://user-images.githubusercontent.com/55466626/74301038-9ac58580-4d06-11ea-8b01-1c97d72c441a.png)

**Comment by AndresPitta** [comment]
Thanks @firasm,

Our reasoning behind it was making a cleaner version for the user (instead of having the user replace the path a probably making mistakes during that process).

**Comment by firasm** [comment]
Yep - I can see the advantages of this. I'm convinced! 

Well done - spark mark!
